name: supertec
description: "A new Flutter project."

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  path: ^1.8.3
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: ProtestGuerrilla
      fonts:
        - asset: assets/fonts/ProtestGuerrilla-Regular.ttf
    - family: NerkoOne
      fonts:
        - asset: assets/fonts/NerkoOne-Regular.ttf
    - family: NewAmsterdam
      fonts:
        - asset: assets/fonts/NewAmsterdam-Regular.ttf
